<?php
/*****************************************************************
 *  download.php
 *  ------------ 
 *  Serve files that were generated by the Assistant (Word, Excel,
 *  PPT, etc.) and saved via save_to_blob() in doc_gen/full/.
 *
 *  Usage:  download.php?f=<basename-from-chat>
 *****************************************************************/

/* 1.  basic parameter check ----------------------------------- */
if (!isset($_GET['f']) || $_GET['f'] === '') {
    http_response_code(400);
    exit('Missing "f" parameter');
}
$basename = basename($_GET['f']);          // strips any .. / slashes

/* 2.  build absolute path & verify ---------------------------- */
define('DOC_GEN_DIR', dirname(__DIR__).'/doc_gen/full');  // adjust if moved

$absPath = DOC_GEN_DIR . DIRECTORY_SEPARATOR . $basename;
if (!is_file($absPath)) {
    http_response_code(404);
    exit('File not found');
}


/* 3.  guess mime-type ----------------------------------------- */
$mime = mime_content_type($absPath) ?: 'application/octet-stream';

/* 4.  send headers & stream ----------------------------------- */
header('Content-Type: ' . $mime);
header('Content-Length: ' . filesize($absPath));
header('Content-Disposition: attachment; filename="' . $basename . '"');

readfile($absPath);
exit;

