<?php
/*****************************************************************
 *  download.php
 *  ------------ 
 *  Serve files that were generated by the Assistant (Word, Excel,
 *  PPT, etc.) and saved via save_to_blob() in doc_gen/full/.
 *
 *  Usage:  download.php?f=<basename-from-chat>
 *****************************************************************/

/* -------------------------------------------------------------
 * Secure download proxy for /doc_gen/full files
 *   ?f=<opaque-local-name>&name=<pretty name shown to user>
 * ------------------------------------------------------------*/
$docDir = dirname(__DIR__).'/doc_gen/full';  // adjust if moved

/* 1.  basic parameter check ----------------------------------- */
if (!isset($_GET['f']) || $_GET['f'] === '') {
    http_response_code(400);
    exit('Missing "f" parameter');
}
$fname  = basename($_GET['f'] ?? '');
$pretty = $_GET['name'] ?? $fname;              // fallback if missing
$path   = realpath("$docDir/$fname");

if (!$path || !str_starts_with($path, realpath($docDir))) {
    http_response_code(404);
    exit('File not found.');
}

header('Content-Type: application/octet-stream');
header('Content-Length: ' . filesize($path));
header('Content-Disposition: attachment; filename="' .
       addslashes($pretty) . '"');
readfile($path);
exit;

