<?php

$topbox = '
<p style="margin-top: 20px;">'.$config['app']['help_text1'].'</p>
<p class="borderedbox" style="text-align: center;">
    <span style="display: flex; justify-content: space-between; width: 90%; margin: 20px auto;">
        <a title="Open a link to the Teams interface" href="'.$config['app']['teams_link'].'" target="_blank">Connect in Teams</a>
        <a title="Open a link to the NHLBI Intranet interface" href="'.$config['app']['intranet_link'].'" target="_blank">Overview and Instructions</a>
        <a title="Open the training video in a new window" href="'.$config['app']['video_link'].'" target="_blank">Training Video</a>
    </span>
</p>
';


$maintext = '
<p>NHLBI Chat stores all data locally in the NIH data center and uses a secure NIH STRIDES cloud account to host AI models. This enables staff to use NHLBI Chat for sensitive data workloads including:</p>
<ul>
<li>Clinical data</li>
<li>Pre-decisional and draft policy </li>
<li>Nonpublic data including scientific data and draft manuscripts</li>
<li>Administrative use cases</li>
</ul>  <p>Currently, PII (excluding SSN/EIN/TIN) may be entered in NHLBI Chat. Ensure that any PII use case is absolutely necessary, and to the best of your knowledge, permission to use this PII has been obtained separately from the impacted person(s). When possible, use de-identified and anonymized data. Please reference guideline #4 below for additional details.</p>

<p>When using NHLBI Chat, please follow these guidelines:</p>
<ol>
<li><b>Human Oversight</b>: Always review and validate outputs generated by NHLBI Chat. Do not base decision-making or policymaking solely on generated outputs. </li>
<li><b>Limitations and Biases</b>: AI models are only as powerful as their training data. Generative AI may generate biased results and may not always generate accurate responses. Generative AI may perform poorly in certain applications. Always validate outputs generated by NHLBI Chat.</li>
<li><b>Ethical use</b>: Follow HHS and NIH policies including <a href="https://wiki.ocio.nih.gov/wiki/index.php/NIH_Artificial_Intelligence_(AI)_Cybersecurity_Guidance" target="_BLANK">OCIO Guidance</a>, <a href="https://intranet.hhs.gov/policy/hhs-policy-securing-artificial-intelligence-technology" target="_BLANK">HHS policy for Securing Artificial Intelligence (AI) Technology</a>, <a href="https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-149.html" target="_BLANK">NOT-OD-23-149 prohibiting Generative AI for NIH Peer Review</a>, and any specific guidance related to your intended use case.</li>
<li><b>PII Use Cases</b>: PII (excluding SSN/EIN/TIN) may be entered into NHLBI Chat. Entering Social Security Number (SSN), Employer Identification Number (EIN) or other Taxpayer ID is not allowed. Please ensure any PII entered does not include SSN/EIN/TIN. If PII (other than SSN/EIN/TIN) is entered, please ensure it is deemed absolutely necessary, and to the best of your knowledge, permission to use this PII has been obtained separately from the impacted person(s). PII is permitted for use and is not limited to genomic data, passport information, driver\'s license numbers, military status, bank account information including credit card numbers, photographic identifiers, medical record numbers, certificate, education records and date of birth. By entering PII you accept that incidental storage of the PII as part of the chat record will occur.</li>
<li><b>Training Data</b>: NHLBI Chat uses commercial models. It is not fine-tuned on NIH, NHLBI, or biomedical topics. Do not expect NHLBI Chat to have any internal knowledge of the NIH or NHLBI.</li>
<li><b>Chat Deletion</b>: NHLBI Chat will automatically delete any chat inactive for 90 days. Deleted chats will be stored for an additional 90 days, after which they will be permanently deleted. This change is to align with record retention schedules for temporary and transitory records. You can always print your chats (using the "Print" button in the application) if you need to maintain a record of your chat.</li>
</ol>
<p>You are accessing a U.S. Government information system, which includes (1) this computer, (2) this computer network, (3) all computers connected to this network, and (4) all devices and storage media attached to this network or to a computer on this network. This information system is provided for U.S. Government-authorized use only.</p>
<p>Unauthorized or improper use of this system may result in disciplinary action, as well as civil and criminal penalties.</p>
<p>By using this information system, you understand and consent to the following.</p>
<p>You have no reasonable expectation of privacy regarding any communications or data transiting or stored on this information system. At any time, and for any lawful Government purpose, the government may monitor, intercept, record, and search and seize any communication or data transiting or stored on this information system.</p>
<p>Any communication or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose.</p>
';
