<p>NHLBI Chat stores all data locally in the NIH data center and uses a secure NIH STRIDES cloud account to host AI models. This enables staff to use NHLBI Chat for sensitive data workloads including:</p>
<ul>
<li>De-identified and anonymized clinical data</li>
<li>Pre-decisional and draft policy </li>
<li>Nonpublic data including scientific data and draft manuscripts</li>
</ul>  <p>Currently, PII and identifiable clinical data is not permitted in NHLBI Chat. Please us de-identified and anonymized data. We are actively working with HHS security to enable this use-case.</p>
<p>Please note that these use cases are specific to NHLBI Chat, which is different than public AI tooling like ChatGPT, Meta.AI, and Google Gemini. When using any public AI tooling, please follow <a href="https://wiki.ocio.nih.gov/wiki/index.php/NIH_Artificial_Intelligence_(AI)_Cybersecurity_Guidance" target="_BLANK">OCIO Guidance</a>, which prohibits these sensitive workloads. Unlike the public tooling, data entered into NHLBI Chat is not shared with Microsoft or OpenAI. This enables the sensitive workloads described above. </p>
<p>When using NHLBI Chat, please follow these guidelines:</p>
<ol>
<li><b>Human Oversight</b>: Always review and validate outputs generated by NHLBI Chat. Do not base decision-making or policymaking solely on generated outputs. </li>
<li><b>Limitations and Biases</b>: AI models are only as powerful as its training data. Generative AI may generate biased results and may not always generate accurate responses. Generative AI may perform poorly in certain applications. Always validate outputs generated by NHLBI Chat.</li>
<li><b>Ethical use</b>: Follow HHS and NIH policies including <a href="https://wiki.ocio.nih.gov/wiki/index.php/NIH_Artificial_Intelligence_(AI)_Cybersecurity_Guidance" target="_BLANK">OCIO Guidance</a>, <a href="https://intranet.hhs.gov/policy/hhs-policy-securing-artificial-intelligence-technology" target="_BLANK">HHS policy for Securing Artificial Intelligence (AI) Technology</a>, <a href="https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-149.html" target="_BLANK">NOT-OD-23-149 prohibiting Generative AI for NIH Peer Review</a>, and any specific guidance related to your intended use case., and any specific guidance related to your intended use case.</li>
<li><b>No PII</b>: PII and identifiable clinical data is currently not permitted in NHLBI Chat. Only use de-identified and anonymized data. </li>
<li><b>Training Data</b>: NHLBI Chat uses commercial models. It is not fine-tuned on NIH, NHLBI, or biomedical topics. Do not expect NHLBI Chat to have any internal knowledge of the NIH or NHLBI.</li>
</ol>
<p>You are accessing a U.S. Government information system, which includes (1) this computer, (2) this computer network, (3) all computers connected to this network, and (4) all devices and storage media attached to this network or to a computer on this network. This information system is provided for U.S. Government-authorized use only.</p>
<p>Unauthorized or improper use of this system may result in disciplinary action, as well as civil and criminal penalties.</p>
<p>By using this information system, you understand and consent to the following.</p>
<p>You have no reasonable expectation of privacy regarding any communications or data transiting or stored on this information system. At any time, and for any lawful Government purpose, the government may monitor, intercept, record, and search and seize any communication or data transiting or stored on this information system.</p>
<p>Any communication or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose.</p>

